@Library('mylibrary')_
pipeline
{
    agent any 
    stages
    {
        stage('Download_Master')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("Maven")
                }
            }
        }
        
        stage('Build_Master')
        {
            steps
            {
                script
                {
                    cicd.buildArtifect()
                }
            }
        } 
        stage('Deployment_Master')
        {
            steps
            {
                script
                {
                    cicd.deployTomcat("MultiBranchPipeline_master", "172.31.2.159","testapp")
                }
            }
        }
        stage('Testing_Master')
        {
            steps
            {
                script
                {
                    cicd.testing("FunctionalTesting", "DeclarativePipelineWithSharedLibrary")   
                }
            }
        }
        stage('Delivery_Master')
        {
           steps
           {
               script
               {
                   cicd.delivery("DeclarativePipelineWithSharedLibrary","172.31.2.253","prodapp")
               }
           }
        }
   }
}   
