@Library('mylibrary')_
pipeline
{
    agent any 
    stages
    {
        stage('Download_loans')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("maven")
                }
            }
        }
        
        stage('Build_loans')
        {
            steps
            {
                script
                {
                    cicd.buildArtifect()
                }
            }
        } 
        }
   }
}   
