@Library('mylibrary')_
pipeline
{
    agent any 
    stages
    {
        stage('Download')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("maven")
                }
            }
        }
        
        stage('Build')
        {
            steps
            {
                script
                {
                    cicd.buildArtifect()
                }
            }
        } 
        stage('Deployment')
        {
            steps
            {
                script
                {
                    cicd.deployTomcat("DeclarativePipelineWithSharedLibrary", "172.31.2.159","testapp")
                }
            }
        }
        stage('Testing')
        {
            steps
            {
                script
                {
                    cicd.testing("FunctionalTesting", "DeclarativePipelineWithSharedLibrary")   
                }
            }
        }
        stage('Delivery')
        {
           steps
           {
               script
               {
                   cicd.delivery("DeclarativePipelineWithSharedLibrary","172.31.2.253","prodapp")
               }
           }
        }
   }
}   
